# Generated by Django 2.1.7 on 2019-02-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0003_wishlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
