# Generated by Django 2.1.7 on 2019-02-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0005_auto_20190228_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='wishlist',
            new_name='wishlist_id',
        ),
    ]
