# Generated by Django 2.1.7 on 2019-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0005_auto_20190228_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='wishlist',
            new_name='wishlist_id',
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
