# Generated by Django 2.1.7 on 2019-03-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0006_auto_20190228_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='wishlist_id',
            new_name='fk_wishlist',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='fk_user',
        ),
    ]
