# Generated by Django 2.1.7 on 2019-03-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0007_auto_20190307_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='gift',
            new_name='fk_gift',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='user',
            new_name='fk_user',
        ),
    ]
