# Generated by Django 2.1.7 on 2019-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0008_auto_20190313_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
