# Generated by Django 2.1.7 on 2019-03-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0012_auto_20190329_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(default='/static/images/default_gift.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
