# Generated by Django 2.1.7 on 2019-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0016_auto_20190329_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(default='default_gift.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
