# Generated by Django 2.1.7 on 2019-04-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwish_app', '0017_auto_20190329_1504'),
        ('sandwish_app', '0012_auto_20190329_1448'),
    ]

    operations = [
    ]
